version: '3.4'

services:
  fktest:
    image: ${DOCKER_REGISTRY-}fktest
    build:
      context: .
      dockerfile: FKTest/Dockerfile
    environment:
      - FKTEST_CONNECTIONSTRINGS__MYSQL=Server=mysql;Database=test;User=root;Password=;default command timeout=20;
  mysql:
    image: mysql:5
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql.conf:/etc/mysql/conf.d/mysql.conf
      - ./data/mysql-import:/docker-entrypoint-initdb.d
    ports: 
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=test
    security_opt:
      - seccomp:unconfined
